version: "3.9"

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: healthcare_api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ../.env

    depends_on:
      - mysql
    volumes:
      - ../:/app
    networks:
      - healthcare_net

  mysql:
    image: mysql:8.0
    container_name: healthcare_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare_api
      MYSQL_USER: healthcare_user
      MYSQL_PASSWORD: healthcare_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - healthcare_net

volumes:
  mysql_data:

networks:
  healthcare_net: